### ISSUE TITLE
Sintesis_Edwin Ortiz Cruz

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/actividad-3-sintesis-EdwinOrtiz1412#2]
[Sintesis_Edwin Ortiz Cruz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-EdwinOrtiz1412/files/12516434/Sintesis_Edwin.Ortiz.Cruz.pdf)

**Comment by MariaJose-1007** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
